<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('users')->insert([
            [
                'first_name' => 'Asuzu',
                'last_name' => 'Zulu',
                'phone_number' => '2405056225',
                'gender' => 'male',
                'street' => '23 cold street',
                'city' => 'Ajah',
                'state' => 'Lagos',
                'bvn' => '12345789016',
                'nin' => '01234567890',
                'email' => 'asuzulu3@gmail.com',
                'dob' => '1986-04-15',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Chris',
                'last_name' => 'Ojo',
                'phone_number' => '08091234567',
                'gender' => 'male',
                'street' => '45 Green Avenue',
                'city' => 'Benin City',
                'state' => 'Edo',
                'bvn' => '23456789013',
                'nin' => '98765432100',
                'email' => 'cojo2492@gmail.com',
                'dob' => '1985-01-01',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Manager',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'John',
                'last_name' => 'Doe',
                'phone_number' => '07012345678',
                'gender' => 'male',
                'street' => '102 Bright Street',
                'city' => 'Benin City',
                'state' => 'Edo',
                'bvn' => '34567890124',
                'nin' => '87654321011',
                'email' => 'johndoe@gmail.com',
                'dob' => '1990-01-15',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Jane',
                'last_name' => 'Doe',
                'phone_number' => '07012345678',
                'gender' => 'female',
                'street' => '102 Bright Street',
                'city' => 'Benin City',
                'state' => 'Edo',
                'bvn' => '45678901234',
                'nin' => '56789012345',
                'email' => 'janedoe@gmail.com',
                'dob' => '1985-07-10',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Chika',
                'last_name' => 'Okoro',
                'phone_number' => '08034567890',
                'gender' => 'female',
                'street' => '55 Banana Road',
                'city' => 'Port Harcourt',
                'state' => 'Rivers',
                'bvn' => '56789012346',
                'nin' => '11223344556',
                'email' => 'chikaokoro@gmail.com',
                'dob' => '1992-03-20',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Uche',
                'last_name' => 'Nwachukwu',
                'phone_number' => '08123456789',
                'gender' => 'male',
                'street' => '10 Chukwuma Lane',
                'city' => 'Enugu',
                'state' => 'Enugu',
                'bvn' => '67890123456',
                'nin' => '22334453667',
                'email' => 'uchendata@gmail.com',
                'dob' => '1988-06-10',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Emeka',
                'last_name' => 'Eze',
                'phone_number' => '09023456789',
                'gender' => 'male',
                'street' => '78 Eze Street',
                'city' => 'Owerri',
                'state' => 'Imo',
                'bvn' => '78901234567',
                'nin' => '33445566779',
                'email' => 'emekaeze@gmail.com',
                'dob' => '1994-08-30',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Olumide',
                'last_name' => 'Adebayo',
                'phone_number' => '08098765432',
                'gender' => 'male',
                'street' => '123 Ojo Crescent',
                'city' => 'Ibadan',
                'state' => 'Oyo',
                'bvn' => '89012345679',
                'nin' => '44556677890',
                'email' => 'olumideadebayo@gmail.com',
                'dob' => '1993-11-12',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Mary',
                'last_name' => 'James',
                'phone_number' => '08111223344',
                'gender' => 'female',
                'street' => '88 Market Road',
                'city' => 'Kaduna',
                'state' => 'Kaduna',
                'bvn' => '90123456789',
                'nin' => '55667781991',
                'email' => 'maryjames@gmail.com',
                'dob' => '1990-05-22',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Adebayo',
                'last_name' => 'Balogun',
                'phone_number' => '07012345679',
                'gender' => 'male',
                'street' => '101 Olorunfemi Street',
                'city' => 'Abeokuta',
                'state' => 'Ogun',
                'bvn' => '23456789014',
                'nin' => '66778899002',
                'email' => 'adebayobalogun@gmail.com',
                'dob' => '1985-09-10',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Zainab',
                'last_name' => 'Aminu',
                'phone_number' => '07098765432',
                'gender' => 'female',
                'street' => '35 Garki Road',
                'city' => 'Abuja',
                'state' => 'FCT',
                'bvn' => '34567890125',
                'nin' => '22334455668',
                'email' => 'zainabaminu@gmail.com',
                'dob' => '1991-02-14',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Customer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Grace',
                'last_name' => 'Obi',
                'phone_number' => '08134567891',
                'gender' => 'female',
                'street' => '21 Unity Lane',
                'city' => 'Ikeja',
                'state' => 'Lagos',
                'bvn' => '56789012347',
                'nin' => '34567890122',
                'email' => 'graceobi@gmail.com',
                'dob' => '1995-09-18',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'James',
                'last_name' => 'Adeola',
                'phone_number' => '08033445566',
                'gender' => 'male',
                'street' => '13 Peace Close',
                'city' => 'Osogbo',
                'state' => 'Osun',
                'bvn' => '67890123457',
                'nin' => '55667788901',
                'email' => 'jamesadeola@gmail.com',
                'dob' => '1991-06-25',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Employee',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Agent Positions
            [
                'first_name' => 'Ibrahim',
                'last_name' => 'Ahmed',
                'phone_number' => '07044556677',
                'gender' => 'male',
                'street' => '9 Independence Street',
                'city' => 'Ilorin',
                'state' => 'Kwara',
                'bvn' => '78901234568',
                'nin' => '66778899003',
                'email' => 'ibrahimahmed@gmail.com',
                'dob' => '1987-03-19',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Agent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Victoria',
                'last_name' => 'Effiong',
                'phone_number' => '08055667788',
                'gender' => 'female',
                'street' => '5 Market Road',
                'city' => 'Calabar',
                'state' => 'Cross River',
                'bvn' => '89012345670',
                'nin' => '77889900112',
                'email' => 'victoriaeffiong@gmail.com',
                'dob' => '1992-04-15',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Agent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'first_name' => 'Samuel',
                'last_name' => 'Okon',
                'phone_number' => '09066778899',
                'gender' => 'male',
                'street' => '3 Tinubu Close',
                'city' => 'Uyo',
                'state' => 'Akwa Ibom',
                'bvn' => '90123456780',
                'nin' => '88990011223',
                'email' => 'samuelokon@gmail.com',
                'dob' => '1990-12-30',
                'password' => bcrypt('password'),
                'profile_image' => null,
                'position' => 'Agent',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
